---
- name: Apply baseline configuration
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - ../group_vars/all.yaml
  vars:
    ansible_user: "{{ bootstrap_login_user_name }}"
    ansible_port: "{{ setup_ssh_port }}"

  roles:
    - role: ssh_hardening
    - role: iptables_firewall
    - role: system_tools

- name: Configure Traefik hosts
  hosts: traefik_hosts
  become: true
  gather_facts: true
  vars_files:
    - ../group_vars/all.yaml
    - ../group_vars/vault.yaml
  vars:
    ansible_user: "{{ bootstrap_login_user_name }}"
    ansible_port: "{{ ssh_hardening_port }}"
  roles:
    - role: docker
    - role: traefik

- name: Apply CrowdSec protection
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - ../group_vars/all.yaml
  vars:
    ansible_user: "{{ bootstrap_login_user_name }}"
    ansible_port: "{{ ssh_hardening_port }}"
  roles:
    - role: crowdsec
